openapi: 3.0.1
info:
  version: "PLACEHOLDER_HIVEMQ_VERSION"
  title: HiveMQ Edge REST API
  x-logo:
    url: "https://www.hivemq.com/img/svg/hivemq-bee.svg"
  contact:
    url: "https://www.hivemq.com"
  description: |
    # Introduction
    HiveMQ Edge's REST API provides endpoints for the following use cases:
    - Authentication
    - Health Checking
    - Exploring Configuration
    ## Errors
    Conventional HTTP response codes are used to indicate the success or failure of an API request. Codes in the 2xx range generally indicate success. Codes in the 4xx range indicate an error that failed given the information provided (e.g., a required parameter was omitted). Codes in the 5xx range indicate an error on the server side.
    For all errors a JSON response with additional details is returned in the format [Problem JSON](https://tools.ietf.org/html/rfc7807).
    ## OpenAPI
    HiveMQ's REST API provides an OpenAPI 3.0 schema definition that can imported into popular API tooling (e.g. Postman) or can be used to generate client-code for multiple programming languages.
